name: 01=Building Blocks
on: push
#on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello 
        run: echo "Hello, World"
  second-job:
    runs-on: ubuntu-latest
    steps:
      - name: Success step 
        run: |
          echo "I will pass!"
          exit 0
      - name: Say goodbye 
        run: echo "Goodbye!"
      