name: 04-using-actions
on:
    push

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
              working-directory: 04-using-actions/react-app #sets default directory for 'run' commands as we have the react setup in that
        steps:
            - name: checkout code
              uses: actions/checkout@v4
              
            - name: Setup Node
              uses: actions/setup-node@v3
              with:
                node-version: '20.x'

            - name: Install dependencies
              run: npm ci
              

            - name: Run Unit Test
              run: npm run test 
              
